### ISSUE TITLE
build: UnicodeDecode error if LANG=C

### ISSUE THREAD

**Issue by fedelibre** [veltzer/openbook#89]
A minor problem, but sometimes I set the terminal LANG to C to print messages in english instead of my locale. This is the error when I run make:

```
$ make
doing [out/openbook.ly]
Traceback (most recent call last):
  File "scripts/wrapper_mako.py", line 101, in <module>
    raise e
  File "scripts/wrapper_mako.py", line 65, in <module>
    filelist=list(filter(is_ready,filelist))
  File "scripts/wrapper_mako.py", line 16, in is_ready
    for line in open(file):
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 7024: ordinal not in range(128)
Makefile:390: recipe for target 'out/openbook.ly' failed
make: *** [out/openbook.ly] Error 1

```

**Comment by veltzer** [comment]
This has been fixed.
